# Jekyll Configuration
title: "Vzhůru vpřed"
description: "Nezávislý a progresivní zpravodajský portál zaměřený na společnost, politiku a moderní měnící se svět"
baseurl: ""
url: "https://vzhuruavpred.cz"  # Production URL for SEO

# SEO Configuration
logo: "/assets/images/logo.png"  # Site logo for structured data
twitter:
  username: vzhuruavpred  # Twitter handle for cards
  card: summary_large_image
facebook:
  app_id: ""  # Facebook App ID (optional)
  publisher: "https://facebook.com/vzhuruavpred"  # Facebook page URL
  admins: ""  # Facebook admin IDs (optional)

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year-:month-:day/:title/
  media:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Redakce"
      image: "/assets/images/default-article.jpg"  # Default OG image for posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      image: "/assets/images/default-page.jpg"  # Default OG image for pages

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Site settings
lang: cs
timezone: Europe/Prague
future: true

# SEO and Analytics
google_analytics: ""  # Add Google Analytics ID when ready
google_site_verification: ""  # Add Google Search Console verification
bing_site_verification: ""  # Add Bing Webmaster verification

# Additional SEO settings
tagline: "Nezávislé zpravodajství pro svobodné občany"
keywords: "zpravodajství, politika, společnost, česká republika, nezávislé noviny, progresivní, pirátské"

# Navigation
navigation:
  - name: "Domů"
    link: "/"
  - name: "Události" 
    link: "/udalosti/"
  - name: "Názory"
    link: "/nazory/"
  - name: "Analýzy"
    link: "/analyzy/"
  - name: "Technologie"
    link: "/technologie/"
  - name: "Kultura"
    link: "/kultura/"
  - name: "Přednášky"
    link: "/prednasky/"

# Social links
social:
  facebook: "#"
  twitter: "#" 
  instagram: "#"
  youtube: "#"
  github: "#"

# Contact information
contact:
  email: "ahoj@vzhuruavpred.cz"
  phone: "+420 123 456 789"
  signal: "+420 123 456 789"
  matrix: "@news:piraten.chat"
  pgp_key: "https://keybase.io/vzhuruavpred/pgp_keys.asc"
  address: "Praha, Česká republika"
  office_hours: "Po-Pá 9:00-17:00"

# Footer configuration
footer:
  copyright_text: "Obsah pod Creative Commons licencí."
  encrypted_note: "Šifrované zprávy vítány 🔐"
  license_url: "https://creativecommons.org/licenses/by-sa/4.0/"
  source_code_url: "https://github.com/tangero/vzhuruvpred"