# Jekyll Configuration
title: "Vzhůru a vpřed"
description: "Nezávislý zpravodajský portál zaměřený na digitalizaci, transparentnost a technologické inovace"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Redakce"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Site settings
lang: cs
timezone: Europe/Prague

# Navigation
navigation:
  - name: "Domů"
    link: "/"
  - name: "Události" 
    link: "/udalosti/"
  - name: "Názory"
    link: "/nazory/"
  - name: "Analýzy"
    link: "/analyzy/"
  - name: "Kultura"
    link: "/kultura/"

# Social links
social:
  facebook: "#"
  twitter: "#" 
  instagram: "#"
  youtube: "#"
  github: "#"