# Cloudflare Pages configuration
name = "vzhuruvpred"
compatibility_date = "2024-09-05"

[build]
command = "bundle exec jekyll build"
publish = "_site"

[build.environment]
JEKYLL_ENV = "production"

# D1 Database for ratings
[[d1_databases]]
binding = "DB"
database_name = "vzhuruvpred-ratings"
database_id = "your-database-id-here"

# KV for rate limiting
[[kv_namespaces]]
binding = "RATINGS_KV"
id = "your-kv-id-here"

[vars]
ENVIRONMENT = "production"