name: Fetch Google Trends

on:
  schedule:
    # Běží každé 3 hodiny
    - cron: '0 */3 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fetch-trends:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 feedparser
    
    - name: Fetch trends from RSS
      run: |
        python << 'EOF'
        import json
        import requests
        import feedparser
        from datetime import datetime
        import xml.etree.ElementTree as ET
        
        print("Načítám Google Trends RSS feed pro Česko...")
        
        # Načteme RSS feed
        rss_url = 'https://trends.google.cz/trending/rss?geo=CZ'
        
        try:
            response = requests.get(rss_url, timeout=30)
            response.raise_for_status()
            
            # Parsujeme XML
            root = ET.fromstring(response.content)
            
            trends_data = []
            
            # Najdeme všechny item elementy
            items = root.findall('.//item')
            
            for idx, item in enumerate(items[:8]):  # Prvních 8 trendů
                # Základní informace
                title = item.find('title')
                title_text = title.text if title is not None else ''
                
                # Traffic information
                traffic = item.find('.//{http://www.google.com/trends/hottrends}approx_traffic')
                traffic_text = traffic.text if traffic is not None else 'Trending'
                
                # Obrázek
                picture = item.find('.//{http://www.google.com/trends/hottrends}picture')
                picture_url = picture.text if picture is not None else ''
                
                # Opravíme relativní URL
                if picture_url and picture_url.startswith('//'):
                    picture_url = 'https:' + picture_url
                
                # Zdroj obrázku
                picture_source = item.find('.//{http://www.google.com/trends/hottrends}picture_source')
                source_text = picture_source.text if picture_source is not None else 'Google Trends'
                
                # První související článek
                news_items = item.findall('.//{http://www.google.com/trends/hottrends}news_item')
                
                if news_items:
                    first_news = news_items[0]
                    news_title = first_news.find('.//{http://www.google.com/trends/hottrends}news_item_title')
                    news_url = first_news.find('.//{http://www.google.com/trends/hottrends}news_item_url')
                    news_source = first_news.find('.//{http://www.google.com/trends/hottrends}news_item_source')
                    
                    news_title_text = news_title.text if news_title is not None else title_text
                    news_url_text = news_url.text if news_url is not None else f"https://www.google.com/search?q={title_text}&tbm=nws"
                    news_source_text = news_source.text if news_source is not None else source_text
                else:
                    news_title_text = title_text
                    news_url_text = f"https://www.google.com/search?q={title_text}&tbm=nws"
                    news_source_text = source_text
                
                # Vytvoříme trend item
                trend_item = {
                    'rank': idx + 1,
                    'query': title_text,
                    'news_title': news_title_text,
                    'news_url': news_url_text,
                    'picture': picture_url,
                    'traffic': f"{traffic_text}+ hledání" if traffic_text != 'Trending' else 'Trending',
                    'source': news_source_text,
                    'explore_url': f"https://trends.google.cz/trends/explore?q={title_text}&geo=CZ"
                }
                
                trends_data.append(trend_item)
                print(f"Trend #{idx+1}: {title_text}")
                print(f"  - Článek: {news_title_text[:50]}...")
                print(f"  - Obrázek: {'✓' if picture_url else '✗'}")
                print(f"  - Traffic: {traffic_text}")
                
        except Exception as e:
            print(f"Chyba při načítání RSS: {e}")
            trends_data = []
        
        # Uložení do JSON
        if trends_data:
            output = {
                'updated': datetime.now().isoformat(),
                'trends': trends_data
            }
            
            with open('_data/trends.json', 'w', encoding='utf-8') as f:
                json.dump(output, f, ensure_ascii=False, indent=2)
            
            print(f"\n✅ Úspěšně načteno {len(trends_data)} trendů z RSS feedu")
        else:
            print("\n❌ Nepodařilo se načíst žádné trendy")
        
        EOF
    
    - name: Commit trends data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _data/trends.json
        git diff --staged --quiet || git commit -m "Update Google Trends data"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main